-- MySQL Script generated by MySQL Workbench
-- Wed Dec 23 16:38:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`gatunek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gatunek` (
  `id_gatunku` INT NOT NULL,
  `nazwa_gatunku` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_gatunku`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zbiory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zbiory` (
  `id_zbiory` INT NOT NULL,
  `data_rozpoczecia` DATE NOT NULL,
  `data_zakonczenia` DATE NULL,
  PRIMARY KEY (`id_zbiory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plony na pozywienie zwierzat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plony na pozywienie zwierzat` (
  `id_plonow na pozywienie zwierzat` INT NOT NULL,
  `jakosc_plonow` VARCHAR(45) NOT NULL,
  `wielkosc_plonow` VARCHAR(40) NOT NULL,
  `zbiory_id_zbiory` INT NOT NULL,
  PRIMARY KEY (`id_plonow na pozywienie zwierzat`),
  INDEX `fk_plony_zbiory1_idx` (`zbiory_id_zbiory` ASC) VISIBLE,
  CONSTRAINT `fk_plony_zbiory1`
    FOREIGN KEY (`zbiory_id_zbiory`)
    REFERENCES `mydb`.`zbiory` (`id_zbiory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zwierzeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zwierzeta` (
  `id_zwierzecia` INT NOT NULL,
  `plec_zwierzeta` VARCHAR(45) NOT NULL,
  `wiek_zwierzecia` INT NOT NULL,
  `gatunek_id_gatunku` INT NOT NULL,
  `plony na pozywienie zwierzat_id_plonow na pozywienie zwierzat` INT NOT NULL,
  PRIMARY KEY (`id_zwierzecia`),
  INDEX `fk_zwierzęta_gatunek1_idx` (`gatunek_id_gatunku` ASC) VISIBLE,
  INDEX `fk_zwierzeta_plony na pozywienie zwierzat1_idx` (`plony na pozywienie zwierzat_id_plonow na pozywienie zwierzat` ASC) VISIBLE,
  CONSTRAINT `fk_zwierzęta_gatunek1`
    FOREIGN KEY (`gatunek_id_gatunku`)
    REFERENCES `mydb`.`gatunek` (`id_gatunku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zwierzeta_plony na pozywienie zwierzat1`
    FOREIGN KEY (`plony na pozywienie zwierzat_id_plonow na pozywienie zwierzat`)
    REFERENCES `mydb`.`plony na pozywienie zwierzat` (`id_plonow na pozywienie zwierzat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zwierzeta na uboj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zwierzeta na uboj` (
  `idzwierzeta na uboj` INT NOT NULL,
  `ilosc zwierzat` VARCHAR(45) NOT NULL,
  `waga` VARCHAR(45) NOT NULL,
  `zwierzeta_id_zwierzecia` INT NOT NULL,
  PRIMARY KEY (`idzwierzeta na uboj`),
  INDEX `fk_zwierzeta na uboj_zwierzęta1_idx` (`zwierzeta_id_zwierzecia` ASC) VISIBLE,
  CONSTRAINT `fk_zwierzeta na uboj_zwierzęta1`
    FOREIGN KEY (`zwierzeta_id_zwierzecia`)
    REFERENCES `mydb`.`zwierzeta` (`id_zwierzecia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`przychod rolnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`przychod rolnika` (
  `id_przychodu_rolnika` INT NOT NULL,
  `doplaty` FLOAT(7,2) NOT NULL,
  `sprzedaz_bydla` FLOAT(7,2) NOT NULL,
  `zwierzeta na uboj_idzwierzeta na uboj` INT NOT NULL,
  PRIMARY KEY (`id_przychodu_rolnika`),
  INDEX `fk_przychód rolnika_zwierzeta na uboj1_idx` (`zwierzeta na uboj_idzwierzeta na uboj` ASC) VISIBLE,
  CONSTRAINT `fk_przychód rolnika_zwierzeta na uboj1`
    FOREIGN KEY (`zwierzeta na uboj_idzwierzeta na uboj`)
    REFERENCES `mydb`.`zwierzeta na uboj` (`idzwierzeta na uboj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maszyny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maszyny` (
  `id_maszyn` INT NOT NULL,
  `ilosc_maszyn` INT NOT NULL,
  `marka` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `typ_maszyny` VARCHAR(45) NOT NULL,
  `data_produkcji` DATE NOT NULL,
  PRIMARY KEY (`id_maszyn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ziemia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ziemia` (
  `id_ziemii` INT NOT NULL,
  `ilość_ziemii` INT NOT NULL,
  `jakosc_gleby` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ziemii`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rasa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rasa` (
  `id_rasy` INT NOT NULL,
  `nazwa_rasy` VARCHAR(45) NOT NULL,
  `gatunek_id_gatunku` INT NOT NULL,
  PRIMARY KEY (`id_rasy`),
  INDEX `fk_rasa_gatunek1_idx` (`gatunek_id_gatunku` ASC) VISIBLE,
  CONSTRAINT `fk_rasa_gatunek1`
    FOREIGN KEY (`gatunek_id_gatunku`)
    REFERENCES `mydb`.`gatunek` (`id_gatunku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rolnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rolnik` (
  `id_rolnika` INT NOT NULL,
  `przychod rolnika_id_przychodu_rolnika` INT NOT NULL,
  `numer_telefonu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rolnika`),
  INDEX `fk_rolnik_przychód rolnika_idx` (`przychod rolnika_id_przychodu_rolnika` ASC) VISIBLE,
  CONSTRAINT `fk_rolnik_przychód rolnika`
    FOREIGN KEY (`przychod rolnika_id_przychodu_rolnika`)
    REFERENCES `mydb`.`przychod rolnika` (`id_przychodu_rolnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pomieszczenia gospodarcze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pomieszczenia gospodarcze` (
  `id_pomieszczen_gospodarczych` INT NOT NULL,
  `numer_pomieszczenia_gospodarczego` INT NOT NULL,
  `wielkosc` ENUM('male', 'srednie', 'duze') NOT NULL,
  `zwierzęta_id_zwierzecia` INT NOT NULL,
  PRIMARY KEY (`id_pomieszczen_gospodarczych`),
  INDEX `fk_pomieszczenia gospodarcze_zwierzęta1_idx` (`zwierzęta_id_zwierzecia` ASC) VISIBLE,
  CONSTRAINT `fk_pomieszczenia gospodarcze_zwierzęta1`
    FOREIGN KEY (`zwierzęta_id_zwierzecia`)
    REFERENCES `mydb`.`zwierzeta` (`id_zwierzecia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gospodarstwo rolne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gospodarstwo rolne` (
  `idgospodarstwo rolne` INT NOT NULL,
  `adres` VARCHAR(45) NOT NULL,
  `kod_pocztowy` VARCHAR(45) NOT NULL,
  `rolnik_id_rolnika` INT NOT NULL,
  `maszyny_id_maszyn` INT NOT NULL,
  `ziemia_id_ziemii` INT NOT NULL,
  PRIMARY KEY (`idgospodarstwo rolne`),
  INDEX `fk_gospodarstwo rolne_rolnik1_idx` (`rolnik_id_rolnika` ASC) VISIBLE,
  INDEX `fk_gospodarstwo rolne_maszyny1_idx` (`maszyny_id_maszyn` ASC) VISIBLE,
  INDEX `fk_gospodarstwo rolne_ziemia1_idx` (`ziemia_id_ziemii` ASC) VISIBLE,
  CONSTRAINT `fk_gospodarstwo rolne_rolnik1`
    FOREIGN KEY (`rolnik_id_rolnika`)
    REFERENCES `mydb`.`rolnik` (`id_rolnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gospodarstwo rolne_maszyny1`
    FOREIGN KEY (`maszyny_id_maszyn`)
    REFERENCES `mydb`.`maszyny` (`id_maszyn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gospodarstwo rolne_ziemia1`
    FOREIGN KEY (`ziemia_id_ziemii`)
    REFERENCES `mydb`.`ziemia` (`id_ziemii`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
